<a href="https://colab.research.google.com/github/arfiaanzenn/tugas3-prak-ML/blob/main/Tugas_Prak_ML_Pert_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tugas Praktikum Machine Learning Pertemuan 3
Nama: Muhammad Farhan Tarigan  
NIM : 1227050089

## Modul 1

## Dataset Air Quality:
Nominal:Name, Measure, Measure Info, Geo TypeName, Geo PlaceName  
Ordinal: -  
Interval: Unique ID, Indicator ID, GeoJoin ID, Time Period, Start Date  
Rasio: Data Value  

## Dataset Prevalensi Balita Stunting:
Nominal: ID, Kode Provinsi, Nama Provinsi, Kode Kab/Kota, Satuan  
Ordinal: -  
Interval: Tahun  
Rasio: Prevalensi Balita Stunting

## Dataset Student Performance:
Nominal: School, Sex, Address  
Ordinal: G1, G2, G3  
Interval: Famsize, Absences  
Rasio: Romantic, Famrel, Goout, Freetime, Age, Travel Time

## Modul 2

In [ ]:
import pandas as pd

# Load data
data = pd.read_csv("DatasetForCoffeeSales2.csv")
display(data.head(10))

# Filter data (City, Category, Product, Quantity)
data.filter(["City", "Category", "Product", "Quantity"]).head()

# Lakukan Sorting Quantity (most)
data.sort_values("Quantity", axis=0, ascending=False, inplace=True, na_position="last")
display(data.head())

# Grouping untuk melihat total sales pada setiap City
grp1 = data.groupby('City')
result = grp1['Final Sales'].aggregate('sum')
print(result)

,Date,Customer_ID,City,Category,Product,Unit Price,Quantity,Sales Amount,Used_Discount,Discount_Amount,Final Sales
0,1/1/2023,32,Riyadh,coffee beans,Colombian,40,14,560,False,0,560
1,1/2/2023,49,Abha,coffee beans,Costa Rica,35,17,595,False,0,595
2,1/3/2023,75,Tabuk,coffee beans,Costa Rica,35,19,665,False,0,665
3,1/4/2023,80,Abha,coffee beans,Ethiopian,45,1,45,False,0,45
4,1/5/2023,78,Hail,coffee beans,Colombian,40,46,1840,True,368,1472
5,1/6/2023,1,Khobar,coffee beans,Colombian,40,32,1280,True,256,1024
6,1/7/2023,95,Buraidah,coffee beans,Brazilian,30,1,30,True,6,24
7,1/8/2023,27,Medina,coffee beans,Colombian,40,33,1320,False,0,1320
8,1/9/2023,73,Hail,coffee beans,Guatemala,35,47,1645,False,0,1645
9,1/10/2023,82,Dammam,coffee beans,Costa Rica,35,4,140,False,0,140

,Date,Customer_ID,City,Category,Product,Unit Price,Quantity,Sales Amount,Used_Discount,Discount_Amount,Final Sales
15,1/16/2023,36,Jeddah,coffee beans,Ethiopian,45,49,2205,True,441,1764
355,12/22/2023,31,Buraidah,coffee beans,Brazilian,30,49,1470,False,0,1470
577,7/31/2024,65,Dammam,coffee beans,Colombian,40,49,1960,True,392,1568
149,5/30/2023,4,Abha,coffee beans,Costa Rica,35,49,1715,False,0,1715
696,11/27/2024,80,Buraidah,coffee beans,Colombian,40,49,1960,True,392,1568

City
Abha        52831
Buraidah    56875
Dammam      59975
Hail        77257
Jeddah      72048
Khobar      59989
Mecca       66420
Medina      64813
Riyadh      68421
Tabuk       51019
Name: Final Sales, dtype: int64

## Modul 3

In [ ]:
import pandas as pd

# Load data
data = pd.read_csv("students.csv")
display(data.head(10))

# Tampilkan informasi mengenai setiap fitur yang dimiliki menggunakan info()
data.info()

# Gunakan fungsi isna() dan sum() pada dataset untuk missing value handling
data.isna().sum()

# Handling missing value menggunakan nilai modus-nya
data['lunch'].fillna(data['lunch'].mode()[0], inplace=True)

# Handling missing value menggunakan nilai mean (karena tipe data fitur reading score adalah float)
data['reading score'].fillna(data['reading score'].mean(), inplace=True)

# Handling missing value menggunakan nilai median (karena tipe data fitur reading score adalah float dan bertipe ordinal)
data['grade'].fillna(data['grade'].median()[0], inplace=True)

# Cek kembali apakah masih ada nilai Nan pada data menggunakan fungsi info()
data.info()

# Interpolate the Missing Value
data['nama_fitur'].interpolate(methode='linear', inplace=True)

#backwardfill the missing value
data['nama_fitur'].filna(method= 'bfill', inplace = True)

#forwardfill the missing value
data['nama_fitur'].filna(method= 'bfill', inplace = True)

# drop Nan Value (Opsi 1)
data['nama_fitur'].dropna(axis=0, inplace=True)

# drop feature with more than 50% are Nan value (Opsi 2)
data['nama_fitur'].drop(axis=1, inplace=True)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,grade
0,female,group B,bachelor's degree,standard,none,72,72.0,74,8.0
1,female,group C,some college,standard,completed,69,90.0,88,7.0
2,female,group B,master's degree,standard,none,90,95.0,93,7.0
3,male,group A,associate's degree,free/reduced,none,47,57.0,44,8.0
4,male,group C,some college,standard,none,76,78.0,75,8.0
5,female,group B,associate's degree,standard,none,71,83.0,78,7.0
6,female,group B,some college,NaN,completed,88,95.0,92,NaN
7,male,group B,some college,free/reduced,none,40,43.0,39,8.0
8,male,group D,high school,free/reduced,completed,64,64.0,67,NaN
9,female,group B,high school,free/reduced,none,38,60.0,50,9.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        975 non-null    object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                976 non-null    float64
 7   writing score                1000 non-null   int64
 8   grade                        985 non-null    float64
dtypes: float64(2), int64(2), object(5)
memory usage: 70.4+ KB

<ipython-input-6-2fe40481feae>:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['lunch'].fillna(data['lunch'].mode()[0], inplace=True)
<ipython-input-6-2fe40481feae>:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['reading score'].fillna(data['reading score'].mean(), inplace=True)

TypeError: 'float' object is not subscriptable